# Generated by Django 4.0.6 on 2022-08-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('nome_colaborador', models.CharField(max_length=100)),
                ('funcao_colaborador', models.CharField(max_length=100)),
                ('email_colaborador', models.EmailField(max_length=100, unique=True)),
                ('whatsapp_colaborador', models.CharField(max_length=14, unique=True)),
                ('senha', models.CharField(max_length=30)),
                ('termo_de_uso', models.BooleanField(default=False, verbose_name='Eu aceito os termos de uso')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas_quiz', models.CharField(default=True, max_length=1, null=True)),
                ('data_de_envio', models.DateTimeField(blank=True, null=True, verbose_name='data de envio')),
                ('cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.CharField(max_length=125)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntas', models.CharField(max_length=255)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
        ),
    ]
