# Generated by Django 4.0.6 on 2022-08-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='whatsapp_colaborador',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
