# Generated by Django 4.0.6 on 2022-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estrelas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pontuacao_parcial',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
